#配置文件 需要复制一份取名为config.toml 放在config/config.toml
[common]
HttpPort = 8000 #http端口 一般用于内网对websocket发送消息
LogMod = 777 #日志文件权限 777|755
MultiplexPort = false #是否监听同一个端口
Name = "gorouting" #名称
PidMod = 777 #pid文件权限 777|755
Pong = false #服务器是否主动pong
WsPort = 20290 #websocket端口
defaultDB = "mysql" #数据库驱动 mysql|
env = "dev" #开发环境 dev|prod可选
httpTimeOut = 5 #http请求超时用于http推送时候的超时设置
maxBody = 51200 #http推送时候可以接受的最大长度单位为字节
readChan = 1000 #写协程管道长度
signKey = "QyAnrxYH7KGBJqMG4t0ymyVVJO5M2zgrP7bBjDL3LOM4PKJ8kOpzziuIrV0bcpXb" #加密密钥
writeChan = 1000 #读协程管道长度
wsTimeOut = 60 #websocket连接超时最大时间 超时服务器将断开
[mysqlDB]
db = "dbname" #数据库名称
maxConnect = 5 #数据库连接池数量
password = "root" #密码
port = 3306 #数据库端口
serverHost = "127.0.0.1" #数据库host
user = "root" #用户名
