#配置文件 需要复制一份取名为config.toml 放在config/config.toml
[common]
env = "dev" #开发环境 dev|prod可选
logMod = 777 #日志文件权限 777|755
maxBody = 51200 #推送时候可以接受的最大长度单位为字节
multiplexPort = false #是否监听同一个端口
name = "Go-WS" #名称暂不支持中文
pidMod = 777 #pid文件权限 777|755
signKey = "QyAnrxYH7KGBJqMG4t0ymyVVJO5M2zgrP7bBjDL3LOM4PKJ8kOpzziuIrV0bcpXb" #加密密钥：用于
[common.http]
httpPort = 8000 #http端口 一般用于内网对websocket发送消息
httpTimeOut = 5 #http请求超时用于http推送时候的超时设置
[common.websocket]
pong = false #服务器是否主动pong
readChan = 1000 #写协程管道长度
writeChan = 1000 #读协程管道长度
wsPort = 20290 #websocket端口
wsTimeOut = 60 #websocket连接超时最大时间 超时服务器将断开
[common.validateMethod]
mold = 1 #mold= 0 #验证类型：0不验证|1jwt验证|2 mysql查询验证;  
name = "token" #name验证的的字符串名称   
[db]
defalut = "mysql"
[db.mysql]
db = "dbname" #数据库名称
maxConnect = 5 #数据库连接池数量
password = "root" #密码
port = 3306 #数据库端口
serverHost = "127.0.0.1" #数据库host
user = "root" #用户名
