[common]
WsPort = 20290
HttpPort = 8000
env = "dev"
signKey="QyAnrxYH7KGBJqMG4t0ymyVVJO5M2zgrP7bBjDL3LOM4PKJ8kOpzziuIrV0bcpXb"
defaultDB="mysql"
wsTimeOut=60
httpTimeOut=5
readChan=1000
writeChan=1000
maxBody=51200
[mysqlDB]
serverHost = "127.0.0.1"
port = 3306
user = "root"
password = "root"
db="dbname"
maxConnect=5